mosch/react-avatar-editor

index.js

I added this to handle the case when a user sends a new image, allowing the passage of a dataURL to the AvatarEditor component after the upload.

Update imageObj in AvatarEditor when image in props changes

---

index.js

* fixed width/height/border passing through props
* cleaned up code

Pass width/height/border through props

---

example/bundle.js
index.js

Most importantly adding support for require.js.
Simply wrapping the original code into a factory, and detect available manager for exporting.

add support for more AMD dependency managers

---

example/bundle.js
index.js

Image libraries (transloadit in my case) often create the cropping area between two given points.  This function calculates the [x1,y1] and [x2,y2] values based on the current width and height compared to the natural width and height.

Function returns cropping area points based on full size image

---

README.md

Took me a while to debug the error once I copy pasted props from README.

add missing = sign for border props in readme

---

README.md
example/bundle.js
index.js

Dragging the image feels sluggish for my application. Optional drag speed will help anybody customize this feature for their application.

do not allow over drag

---

example/bundle.js
index.js

Dragging the image feels sluggish for my application. Optional drag speed will help anybody customize this feature for their application.

allow control over how fast image drags

---

index.js
package.json

* check if touch is supported
* use right properties / events (depend on touch supported)
This give ability to resize/move image on mobile

Add touch capabilities

---

example/bundle.js
index.js

Fix #15 - the initial image should fill up the whole viewport instead of being contained with white space

Fix a bug that causes the wrong initial image size

---

index.js

@mosch From what I can tell and my tests this solves all image positions for me. I did not go through calculatePosition to see if this can be solved better.

Use image.x and image.y when cropping. Fixes #7

---

.gitignore
index.js

@mosch This should solve the last bug re introduced from my last pull request. I still have a bounds issue when try to get to the drag all the way to the bottom of an image, but it seems like I had that problem before any of my pr's. It might depend on the image as well. I will need to check. Thanks!

Fix for bounds issue introduced from last pull request that fixed #7

---

README.md
index.js

This PR adds a property to the avatar editor that will be called once the image as been loaded into the editor. Also adds some missing documentation and documentation for the new property

Add Property onImageReady

---

README.md

using quotes in JSX makes the values strings. The Editor needs numbers. Fixed the Readme to reflect that.

don't use quotes for numbers

---

index.js
package.json

Minor changes to support react-0.14.0-rc1. I'll update this PR when there's a full release.

updates to react 0.14

---

README.md
dist/index.js
example/app.js
example/bundle.js
index.js

Add a method to retrieve the cropping rect with relative coords.
Update the docs and the example.
Fixes #28

Expose the cropping rect (getCroppingRect)

---

example/app.js
example/bundle.js

Replace deprecated React.render with ReactDOM.render in the example app.

Tiny fix: Use ReactDOM.render

---

README.md
dist/index.js
index.js

Hi mosch!
We have a use-case where it would be useful to have this callback to update a preview image once the user has paused interaction.
Thought it may be useful for other people too - what do you think?
Thanks!

add onMouseUp prop

---

README.md
index.js

Spotted a problem: If you upload a new image, the x and y will not be resettet

Revert "Add ability to set x and y from props"

---

index.js

That is, without zoom, as suggested in #54.

getImage() returns image in original resolution

---

README.md

🔧 Update getImage() doc in README.md

---

dist/index.js

Hello. I resolved this issue.
https://github.com/mosch/react-avatar-editor/issues/73#issuecomment-224500859

fix empty dist

---

.babelrc
dist/index.js

Hi,
I just add `.babelrc`.
Without config file you command `npm run build` failed because `babel-plugin-transform-object-rest-spread` plugin is not loaded.
```
> babel --modules umd index.js > dist/index.js
SyntaxError: index.js: Unexpected token (413:16)
411 |             height: this.getDimensions().canvas.height,
412 |             style: {
> 413 |                 ...defaultStyle,
|                 ^
414 |                 ...this.props.style
415 |             }
416 |         }
```

Add babelrc file

---

README.md
package.json
webpack.config.js

I was adding webpack-dev-server for easier development. It also has hot reload tool for demo page.

add webpack-dev-server

---

README.md

Use ES6 code style in usage examples.

---

docs/App.jsx

Allows seeing the effect on the position of dragging the image around, and also (when control image is checked) allows panning the image via the sliders.

Add some position sliders to the demo page

---

docs/App.jsx

Account for padding when determining pixel border radius in demo

---

webpack.config.js

Makes debugging a little easier :)

Enable source maps in demo

---

src/index.js

I removed my fork and created it again to be sure everything is ok. Let me know if everything is ok now. ;)

handleMouseEvent update

---

README.md

Use a class field, which auto binds the method to the instance.

Fix example how to access an image

---

README.md
src/index.js

Hi there!
Thanks for a great react component. I had a use case where I needed different x and y borders to allow selecting between different aspect ratios.  
Would you be interested in this too?
Fixes #140 and possibly #79

Support x and y borders

---

src/index.js

Removing this one line adds support for correct drag'n'move for any rotation.

enables drag and move for all angles when rotate

---

src/index.js

Check if file API is supported before attempting to use it

---

docs/App.jsx

This makes it much easier to test and refer to the behaviour when scale < 1.

Add 'Allow Scale < 1' option to demo

---

package.json

Updating to allow to support version React 16.0 in the dependencies.

support version React 16.0 in the dependencies.

---

README.md

Update over the issue #226 @mosch

Added instruction to convert canvas to image URL

---

src/index.js

cf. https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate

Stop using componentWillUpdate

---

src/index.js

Stop using findDOMNode

---

docs/App.jsx
docs/javascripts/scale.fix.js
src/index.js

- Disable only with specific rules
- Enable lint after disable
- Remove unnecessary disables

Clean up the ESLint disable comments

---

docs/App.jsx
package.json
rollup.config.js
src/index.js
yarn.lock

In the first commit of this PR, I added a props property named "disableCanvasRotation" that should disable canvas rotation when rotating the image, I also added an example for the demo.
This should fix the bug in this issue : https://github.com/mosch/react-avatar-editor/issues/299
In the second commit of this PR, I fixed the babelHelpers error in this issue : https://github.com/mosch/react-avatar-editor/issues/340
And then in the last commit, I upgraded the Webpack package.

Fix canvas rotation when rotating the image

---

src/index.js

Fix disableCanvasRotation prop psssing to canvas DOM element

---

docs/App.jsx
src/index.js

I have introduced another property `backgroundColor` which can be any format of color or a nullish value. If a nullish value is passed, this feature will be ignored.

➕ Background color change function for transparent images

---

package.json

Updated peer dependency for React 17

---

docs/App.jsx

See https://github.com/mosch/react-avatar-editor/issues/355

Set the boundary for rotate value

---

packages/lib/src/index.ts

Feature request https://github.com/mosch/react-avatar-editor/issues/370

Adding optional 'Rule of Three' grid.

---

README.md

fixed a javascript example

---

DESIGN.md
README.md

👋
As I'm a big fan of react-avatar-editor I'd like to invite you to get more visibility across designers to help you improve the look and feel and general UX of the component. 
I can imagine a lot of designers being eager to pimp the demo page or help you with the styling of the crop/mask/resize behaviours.  (which could be great good first issues)
As the guidelines mention you'd need to add 2 labels to your project to help them identify / create potential issues – namely: `design: 💅required` and `design: 💡idea`

docs(design): add design contribution guidelines

---

packages/lib/src/index.ts

Use correct context inside of getImage()
