- index.js
There are devices that with mouse and touch support at the same time. In these cases, it makes sense to track both mouse and touch dragging.
> Use both touch and mouse events

- index.js
I have an app that exposes modules as global variables (i.e. not a CommonJS environment).
The names used in this module's umd block aren't working. Seems like [line 12](https://github.com/mosch/react-avatar-editor/blob/master/index.js#L12) should change from
```js
root.returnExports = factory(root.react, root);
```
to 
```js
root.AvatarEditor = factory(root.React, root);
```
1. Renamed this module's global to `AvatarEditor` to match the readme examples
2. When exposing itself as a global, react uses the name `React`
> Changing names used with browser globals

- package.json
Putting Reactify in the transform list breaks Browserify when it can't find it installed. Since you are providing a pre-compiled file and pointing to it, you don't need to put Reactify in the Transform list.
> You don't need Reacitify

- index.es5.js
- index.js
To accomplish that, we now check for `window` and `navigator` being defined
before referencing them. Without this added step, a ReferenceError is thrown
when used as part of a server-side rendered component.
> Adds support for server-side rendering

- index.js
From React's docs: "getDOMNode is deprecated and has been replaced with
React.findDOMNode()."
> Replace deprecated method getDOMNode

- dist/index.js
- example/app.js
- example/bundle.js
- index.js
Many websites/apps display profile pics with rounded corners.
This feature enables them to give users a more accurate preview of what the final image will look like.
Note that ``getImage()`` still produces a square-cornered image, without erasing the hidden corners.
This should be okay, as the corners are typically rounded on the webpage with CSS ``border-radius``.
> Add borderRadius property for rounded corners

- README.md
- dist/index.js
- index.js
In this pull request, there are two changes:
- add onMouseMove support to make it closely similar to facebook
- fix onLoadSuccess return NaN values in imageState
> onMouseMove Support + fix onLoadSuccess bug

- README.md
- index.js
As I have argued before, ``getImage()`` should return a canvas instead of a data URL, for the sake of simplicity and flexibility.
* Lets us get the dataURL or the blob, draw the canvas ontop of another, display it directly in the DOM, or whatever.
* Renders the two arguments to ``getImage()`` unneeded.
* Calling ``getImage(type, quality)`` is no harder than calling ``getImage().toDataURL(type, quality)``.
> getImage() returns a <canvas> instead of data URL

- index.js
- package.json
Noticed that the mouseUp handler is always triggered regardless of whether a drag is in progress.  This gets kinda spammy, and also makes the handler a little bit useless, because it's invoked whenever a mouseup event occurs anywhere on the document, even if the user is not interacting with the avatar editor.
> Trigger mouse up during drag only

- docs/bundle.js
- package.json
- src/index.js
Based on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin users can select "anonymous" or "use-credentials" for crossorigin attribute of Images
These changes allow users to select the cross-origin value for Images.
default value: "anonymous" for supporting previous versions
valid values: '', 'anonymous' or 'use-credentials'
https://github.com/mosch/react-avatar-editor/issues/142
> Supporting option for Image cross origin 

- src/index.js
Little cleanup - noticed that handleMouseMove is bound to `this` twice in the constructor. :)
> Remove repeated bind of handleMouseMove

- README.md
- src/index.js
Hey @mosch!  Thanks for working on this project, I hope we can work together to get this additional functionality into the codebase. :D
In order to achieve this functionality I was initially looking at allowing the user to pass a croppingRect instead of a scale prop and using that to set the scale and the position of the cropped area.  However that approach has a couple of problems:
1. It means the consumer of the component has to do non-trivial math to keep the x and y coordinates in the cropping rect consistent with the width and height as the scale is adjusted.
1. It makes the API more complex - we would have to decide order of precedence between the scale prop and the croppingRect prop, and document this behaviour.
Instead, I went with the approach of adding a new prop which can live …
> Add ability to control position of cropping area via prop

- docs/App.jsx
- src/index.js
In non-square canvases, images were previously rendered incorrectly in vertical rotations both in the image selector itself, and in the image data returned by `getImage`.  This issue was due to the swap of the x and y dimensions of the canvas in vertical orientations.  This commit adds a translate which cancels this out and causes the images to render correctly again.
> Fix rendering of rotated images

- docs/App.jsx
Previously for non-square sizes, the preview was rendering an elliptical shape instead of a pill shape, because the border radius was specified as a percentage.  This commit changes the styling to use a pixel border radius to get the appropriate pill shape.
**Before**
**After**
> Make border radius in demo preview consistent with component

- docs/App.jsx
- src/index.js
* Previously the max/min of the x & y values in the cropping rect were calculated based on the assumption that scale >= 1, and that you wouldn't want any whitespace in your resultant image.
* Now, if scale >= 1, the bounds are the same as they were before, but if scale < 1, you can drag the image anywhere within the editor view (all the way to immediately outside the visible area).
* As the incorrect scaling behaviour described in #150 was caused by the max/min for x & y being calculated correctly when scale < 1, this fixes #150.
* Update `ImageWithRect` component so that it works when scale < 1 - in this situation, the cropping rect fills the canvas and the image is rendered inside it.  We could go further here - in this situation we don't show the part of the image that's outside the …
> Handle scale < 1

- README.md
- src/index.js
Setting crossOrigin='anonymous' on the Image before making the request causes the Image to fail to load in some circumstances<sup>1</sup> when the server does not include CORS headers on its response.  This was hard to track down, and therefore I suggest that we remove the default crossOrigin prop, meaning that users who wish to load CORS-enabled images in the ReactAvatarEditor will need to explicitly set it.  With this new behaviour, calls to getImage() and getImageScaledToCanvas() will fail when non-CORS enabled images are used, but the component will otherwise work as expected.  Conversely, with the current default of 'anonymous', the component fails to render, generating errors in the console that aren't linked to the component.
<sup>1</sup>: For me, the image fails to load in the …
> Remove default crossOrigin prop

- docs/App.jsx
- docs/javascripts/scale.fix.js
- package.json
- src/index.js
- webpack.config.js
- yarn.lock
Hi fellow coworker 🕴,
Those are just some small changes regarding the built-in prop types that were recently extracted to a separate package by the React team.
In order to enhance the code quality (I saw some StandardJS comments), I've provided a new linting script (which is also now part of the *npm* prepublish step).
Thanks for your great work 👍.
> Update PropTypes to get in sync with React v15.5.4 & add better linting via StandardJS

- README.md
- docs/App.jsx
- package.json
- src/index.js
* `image` prop can now contain a `File` or string.
* Add information about `image` prop to README (and a little bit of general cleanup of the props table).
* Add file chooser to demo to make it easy to test this functionality.
> Add support for passing File in image prop

- src/index.js
Previously the canvas was scaled before applying the rotation, but the transform origin did not take account of the scaling, which meant that the image was not rotated around its center, causing it to ping off somewhere else off-canvas.  Now, the scale factor is applied after the transform, so there's no need to account for it.
Fixes #183.
> Fix image painting when rotate !== 0

- README.md
- src/index.js
It is possible that the parent element is also draggable, but if this is an image selection, parent handler should not be triggered. Passing event allows calling a `stopPropagation` function and make the parent handler not receive the event.
Thanks!
> Pass event to the handler on mouse/touch move

- README.md
- src/index.js
Hi @mosch, 
This PR allows toggling off the drop behavior. For my usecase, the parent element was already handling drop behavior and I was looking to pass the file directly into the editor. I'll have another PR soon on that functionality.
Thanks!
> Adds ability to disable drop handling behavior

- docs/App.jsx
Update over the issue #230 . Below image (localhost:8080) shows the height is not overlapping the inputs.
> Corrected the height of Image in Demo

- package.json
- src/index.js
- src/utils/load-image-file.js
- webpack.config.js
- yarn.lock
Because of the latest issues regarding `regeneratorRuntime` related to `babel-preset-env` we should drop `async`/`await` for now until we get that sorted out.
> Drop async/await for now until we get it sorted out.

- src/index.js
-`image.onerror` resulted in an uncaught error in Promise
-`onLoadFailure` was never called in the code
> fix: handle uncaught error when load image fails

- src/index.js
#250 
This is the recommended way to deal with Chrome having changed touch events to being "passive" by default and thus ignoring calls to `preventDefault()`.
This fixes the avatar panning being difficult in Chrome due to the browser's default touch handling kicking in (which scrolls the page instead).
See https://developers.google.com/web/updates/2017/01/scrolling-intervention#breakage_and_guidance
> #250 Disable touch-actions on avatar canvas

- src/index.js
Remove disableBoundaryChecks in default props since it'll be falsy by default
> fixes disableBoundaryChecks warning

- package.json
- src/index.js
This is related to https://github.com/mosch/react-avatar-editor/issues/250 ; the fix that worked for Chrome doesn't work for iOS.  This commit makes things the same on both mobile Chrome and Safari: when the user pans avatar editor, it doesn't also scroll the page.
This should also address https://github.com/mosch/react-avatar-editor/issues/258 (and thanks to karltaylor whose comment helped with this fix).
What was needed was a simple `evt.preventDefault()` inside mouseMove; however Safari will ignore this unless `{passive: false}` passed to addEventListener.  Because _that_ is not completely cross-browser compatible, it needed a feature test.
Also included a small Jest fix so the tests passed during development.  Manually tested that the scrolling works on both mobile Chrome and Safari …
> Stop double-scrolling on iOS Safari

- src/index.js
#249  
When passing an empty image (null, undefined, etc) in order to clear the canvas after you initially loaded an image the old image in the state is not cleared thus repainting the old one on the canvas we just cleared when componentDidUpdate fires.
> Reset the image in state when empty image is passed as a prop to avoid repainting the old one in componentDidUpdate

- src/index.js
Hi! First, thank you for this package -- very useful! 
I just upgraded to the latest 12.0.0-beta release and I'm no longer able to load the component due to max update depth exceeded errors. I looked at the latest commits and found the issue:
```
componentDidUpdate(prevProps, prevState) {
if (...) {...
} else if (!this.props.image) {
this.clearImage()
}
}
clearImage = () => {
...
this.setState({
image: defaultEmptyImage,
})
}
```
If the image prop value is null/undefined (which may be the case if you are waiting on an async call to load a dataUrl or to do some sort of check on upload), the setState() in `clearImage` is going to trigger a `componentDidUpdate`, which will again call `clearImage -> setState()`, and so on in an infinite loop.
This PR addresses the issue by checking to make …
> prevent setState loop when image prop value is null

- README.md
Hello,
Thanks a lot for this super useful component! It's been a breeze to setup and use :).
This PR updates the example on Dropzone to reflect the changes to the `react-dropzone` API. Notably, they are now using a render prop and the current example will fail on proptypes checking.
Hope that's useful. Let me know if any changes are required.
Cheers,
Thibaut
> Update Dropzone example

- packages/lib/src/index.ts
This changes is fixing the issue: https://github.com/mosch/react-avatar-editor/issues/371
I'm unable to get the project to build as-is, but I'm running a vanilla JS (no Typescript) version, and this is what I needed to get the mobile version to work correctly.
> Fix 371 dragging works on mobile

- README.md
Fixes a variable name mismatch in the examples.
> docs: update example in README.md

- packages/lib/src/index.ts
Fix floating point errors when computing width and height by roudning to the nearest integer value. Fixes #392 
Some calculations will return with a non integer value:
> Fix floating point calculations

- packages/lib/src/index.ts
Hi! While trying to use the latest beta version, I noticed a mismatch between types coming from `Props` interface and the actual component props. The mismatch is mainly about `border` and `color`. 
The issue comes from the `PropsWithDefaults` type, which overrides the `Props` interface types with ones inferred from `defaultProps`. 
This PR makes `Props` the source, while `defaultProps` is only used to mark some as required.
> Fix props types
